export const OANDA_CODES = {
  WHEAT_USD: "Wheat",
  XAU_AUD: "Gold/AUD",
  USD_ZAR: "USD/ZAR",
  CAD_JPY: "CAD/JPY",
  XAU_CAD: "Gold/CAD",
  CAD_HKD: "CAD/HKD",
  CH20_CHF: "Switzerland 20",
  EUR_NOK: "EUR/NOK",
  USB05Y_USD: "US 5Y",
  UK100_GBP: "UK 100",
  HK33_HKD: "Hong Kong",
  XAG_EUR: "Silver/EUR",
  USD_PLN: "USD/PLN",
  GBP_AUD: "GBP/AUD",
  GBP_CHF: "GBP/CHF",
  USD_THB: "USD/THB",
  USD_SGD: "USD/SGD",
  EUR_SEK: "EUR/SEK",
  AUD_JPY: "AUD/JPY",
  EUR_ZAR: "EUR/ZAR",
  TRY_JPY: "TRY/JPY",
  SGD_JPY: "SGD/JPY",
  NZD_JPY: "NZD/JPY",
  US2000_USD: "US Russ",
  AUD_SGD: "AUD/SGD",
  AUD_HKD: "AUD/HKD",
  WTICO_USD: "West Texas",
  XAG_AUD: "Silver/AUD",
  GBP_USD: "GBP/USD",
  USD_MXN: "USD/MXN",
  EUR_CHF: "EUR/CHF",
  AUD_CHF: "AUD/CHF",
  XAU_HKD: "Gold/HKD",
  ZAR_JPY: "ZAR/JPY",
  CHF_ZAR: "CHF/ZAR",
  HKD_JPY: "HKD/JPY",
  SUGAR_USD: "Sugar",
  EUR_PLN: "EUR/PLN",
  XAU_JPY: "Gold/JPY",
  XCU_USD: "Copper",
  XAG_HKD: "Silver/HKD",
  USD_HKD: "USD/HKD",
  XAG_JPY: "Silver/JPY",
  EUR_SGD: "EUR/SGD",
  USD_SEK: "USD/SEK",
  GBP_SGD: "GBP/SGD",
  GBP_NZD: "GBP/NZD",
  XAU_NZD: "Gold/NZD",
  GBP_HKD: "GBP/HKD",
  EUR_HKD: "EUR/HKD",
  USD_JPY: "USD/JPY",
  EUR_TRY: "EUR/TRY",
  CORN_USD: "Corn",
  USD_CHF: "USD/CHF",
  AUD_NZD: "AUD/NZD",
  AU200_AUD: "Australia 200",
  USB30Y_USD: "US T",
  FR40_EUR: "France 40",
  SGD_CHF: "SGD/CHF",
  JP225_USD: "Japan 225",
  GBP_ZAR: "GBP/ZAR",
  USD_NOK: "USD/NOK",
  XAG_USD: "Silver",
  AUD_USD: "AUD/USD",
  EUR_HUF: "EUR/HUF",
  XAG_GBP: "Silver/GBP",
  CAD_SGD: "CAD/SGD",
  NAS100_USD: "US Nas",
  DE10YB_EUR: "Bund",
  EUR_CAD: "EUR/CAD",
  USD_HUF: "USD/HUF",
  XAU_CHF: "Gold/CHF",
  NZD_SGD: "NZD/SGD",
  EUR_JPY: "EUR/JPY",
  NATGAS_USD: "Natural Gas",
  GBP_PLN: "GBP/PLN",
  XAG_NZD: "Silver/NZD",
  USB10Y_USD: "US 10Y",
  EU50_EUR: "Europe 50",
  SG30_SGD: "Singapore 30",
  CHF_JPY: "CHF/JPY",
  XAG_CAD: "Silver/CAD",
  XAG_CHF: "Silver/CHF",
  XAG_SGD: "Silver/SGD",
  XAU_EUR: "Gold/EUR",
  USD_CNH: "USD/CNH",
  XAU_GBP: "Gold/GBP",
  AUD_CAD: "AUD/CAD",
  UK10YB_GBP: "UK 10Y",
  SPX500_USD: "US SPX",
  USD_DKK: "USD/DKK",
  BCO_USD: "Brent Crude",
  EUR_DKK: "EUR/DKK",
  SOYBN_USD: "Soybeans",
  CN50_USD: "China A50",
  USD_CZK: "USD/CZK",
  EUR_GBP: "EUR/GBP",
  NZD_USD: "NZD/USD",
  USD_CAD: "USD/CAD",
  EUR_CZK: "EUR/CZK",
  CAD_CHF: "CAD/CHF",
  NZD_HKD: "NZD/HKD",
  ESPIX_EUR: "Spain 35",
  NZD_CHF: "NZD/CHF",
  XAU_XAG: "Gold/Silver",
  XPD_USD: "Palladium",
  XAU_USD: "Gold",
  XPT_USD: "Platinum",
  JP225Y_JPY: "Japan 225",
  EUR_USD: "EUR/USD",
  CHINAH_HKD: "China H",
  GBP_JPY: "GBP/JPY",
  USD_TRY: "USD/TRY",
  CHF_HKD: "CHF/HKD",
  DE30_EUR: "Germany 30",
  NZD_CAD: "NZD/CAD",
  US30_USD: "US Wall",
  NL25_EUR: "Netherlands 25",
  USB02Y_USD: "US 2Y",
  EUR_NZD: "EUR/NZD",
  XAU_SGD: "Gold/SGD",
  GBP_CAD: "GBP/CAD",
  EUR_AUD: "EUR/AUD,",
};
